name: GraalVM Native

on:
  pull_request:
    branches: [stable, development, '*.x']
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'

jobs:
  build:
    concurrency:
      group: pull_request_native-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.module }}-${{ matrix.java-version }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21, 22 ] #Latest two LTS + latest non-LTS.
    timeout-minutes: 120
    steps:
      # Clone timefold-solver
      # Need to check for stale repo, since Github is not aware of the build chain and therefore doesn't automate it.
      - name: Checkout timefold-solver to access the scripts
        uses: actions/checkout@v4
        with:
          path: './timefold-solver'
          repository: 'TimefoldAI/timefold-solver'
      - name: Find the proper timefold-solver repo and branch
        env:
          CHAIN_USER: ${{ github.actor }}
          CHAIN_BRANCH: ${{ github.head_ref }}
          CHAIN_REPO: "timefold-solver"
          CHAIN_DEFAULT_BRANCH: ${{ endsWith(github.head_ref, '.x') && github.head_ref || 'main' }}
        shell: bash
        run: |
          ./timefold-solver/.github/scripts/check_chain_repo.sh
          rm -rf ./timefold-solver
      - name: Checkout the proper timefold-solver branch
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_CHAIN_USER }}/${{ env.TARGET_CHAIN_REPO }}
          ref: ${{ env.TARGET_CHAIN_BRANCH }}
          path: './timefold-solver'
          fetch-depth: 0 # Otherwise merge in the next step will fail on account of not having history.
      - name: Prevent stale fork of timefold-solver
        env:
          BLESSED_REPO: "timefold-solver"
          BLESSED_BRANCH: ${{ endsWith(github.head_ref, '.x') && github.head_ref || 'main' }}
        shell: bash
        working-directory: ./timefold-solver
        run: .github/scripts/prevent_stale_fork.sh

      # Clone timefold-quickstarts
      # No need to check for stale repo, as Github merges the main repo into the fork automatically.
      - name: Checkout timefold-quickstarts
        uses: actions/checkout@v4
        with:
          path: './timefold-quickstarts'

      # Build and test
      - name: "Setup GraalVM native image"
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Quickly build timefold-solver
        working-directory: ./timefold-solver
        run: mvn -B -Dquickly clean install
      - name: Test timefold-quickstarts in Native mode
        working-directory: ./timefold-quickstarts
        run: mvn -B -Dnative verify